### ISSUE TITLE
请问作者后续有没有开源数据集的计划呢

### ISSUE THREAD

**Issue by lwbmowgli** [ruleGreen/SAFARI#1]

**Comment by hrwise-nlp** [comment]
感谢对我们工作的关注，我正在和其他co-author和相关方协调，争取和我们最新的工作一起开源出来。欢迎持续关注，预计这个月底或者下个月初。

**Comment by py-rgb** [comment]
请问数据集开源了吗

**Comment by hrwise-nlp** [comment]
just upload it, please check kbp.zip
