### ISSUE TITLE
clone下来的项目中缺少app相关的包

### ISSUE THREAD

**Issue by leap233** [ruleGreen/SAFARI#2]
在项目中的 unsupervised/main.py 文件导入了
from app.sample_resp_cralwer import SampleRespCrawler
from app.chatgpt_resp_cralwer import ChatgptRespCrawler
from app.huggingface_resp_crawler import HuggingFaceRespCrawlerBase
这个包,请问这个包是第三方库还是自定义的工具类。我在项目中并没有发现这个包的定义。

![image](https://github.com/ruleGreen/SAFARI/assets/66467623/457e6801-493a-4227-ba71-dad1bb7c1047)

![image](https://github.com/ruleGreen/SAFARI/assets/66467623/aee3418f-0a0f-4ecf-a9df-eb5e5b053b5e)

**Comment by hrwise-nlp** [comment]
Thank you for your attention on our work. This is a self-defined class to make us to call models released on HuggingFace such as ChatGLM in our paper. You can define on your own.

**Comment by peng913** [comment]
> 在项目中的 unsupervised/main.py 文件导入了 from app.sample_resp_cralwer import SampleRespCrawler from app.chatgpt_resp_cralwer import ChatgptRespCrawler from app.huggingface_resp_crawler import HuggingFaceRespCrawlerBase 这个包,请问这个包是第三方库还是自定义的工具类。我在项目中并没有发现这个包的定义。
兄弟，你跑出来了吗
